name: starwars_app
description: Aplicación de Star Wars usando SWAPI y Firebase
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase core + Firestore + Auth
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4

  # Login con cuenta Google (si lo estás usando)
  google_sign_in: ^6.1.6

  # Para hacer requests a SWAPI
  http: ^0.13.6

  # Iconos de iOS estilo Cupertino
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
