// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBERGBu-GOfZ2veqCIxzYvb9wFQP2D6wfA',
    appId: '1:463713572856:web:7328da13c9c616c1ef280d',
    messagingSenderId: '463713572856',
    projectId: 'starwarsapi-3868b',
    authDomain: 'starwarsapi-3868b.firebaseapp.com',
    storageBucket: 'starwarsapi-3868b.firebasestorage.app',
    measurementId: 'G-92SH8TP1DG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiG0T2AKLNVPFhPeZbY7lH4qWIXf43LVo',
    appId: '1:463713572856:android:c3d4d81859002e98ef280d',
    messagingSenderId: '463713572856',
    projectId: 'starwarsapi-3868b',
    storageBucket: 'starwarsapi-3868b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4cMDCyakjRtBhL1iOs2_61v-SHa2ygEw',
    appId: '1:463713572856:ios:69f603d18bbe0055ef280d',
    messagingSenderId: '463713572856',
    projectId: 'starwarsapi-3868b',
    storageBucket: 'starwarsapi-3868b.firebasestorage.app',
    iosBundleId: 'com.example.starwarsProjectExamen2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4cMDCyakjRtBhL1iOs2_61v-SHa2ygEw',
    appId: '1:463713572856:ios:69f603d18bbe0055ef280d',
    messagingSenderId: '463713572856',
    projectId: 'starwarsapi-3868b',
    storageBucket: 'starwarsapi-3868b.firebasestorage.app',
    iosBundleId: 'com.example.starwarsProjectExamen2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBERGBu-GOfZ2veqCIxzYvb9wFQP2D6wfA',
    appId: '1:463713572856:web:1fc9ced7156cc5e5ef280d',
    messagingSenderId: '463713572856',
    projectId: 'starwarsapi-3868b',
    authDomain: 'starwarsapi-3868b.firebaseapp.com',
    storageBucket: 'starwarsapi-3868b.firebasestorage.app',
    measurementId: 'G-VPPL0P2JR5',
  );
}
